spring:
    servlet:
      multipart:
        max-file-size: 128KB
        max-request-size: 128KB
    http:
      multipart:
        enabled: false
    thymeleaf:
      cache: false
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
      datasource:
        url: jdbc:hsqldb:file:~/.h2/testdb
        username: sa
        password: sa
        driverClassName: org.hsqldb.jdbcDriver

debug: true
logging:
  level:
    org.springframework.security: INFO